"""Add thumbnail image to orgs

Revision ID: 040ccb1d456e
Revises: 83b6d9d6f57a
Create Date: 2024-09-27 10:23:50.508031

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '040ccb1d456e'
down_revision: str | None = '83b6d9d6f57a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('thumbnail_image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'thumbnail_image')
    # ### end Alembic commands ###
