"""Org Scripts

Revision ID: eb10d15465b3
Revises: a5afa69dd917
Create Date: 2025-06-08 18:12:18.853988

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'eb10d15465b3'
down_revision: str | None = 'a5afa69dd917'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('scripts', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'scripts')
    # ### end Alembic commands ###
