from typing import Literal

from pydantic import BaseModel


class AttachmentData(BaseModel):
    """Attachment data sent with a message"""
    type: Literal['image', 'video', 'file', 'youtube']
    name: str
    url: str | None = None  # For YouTube links
    content_base64: str | None = None  # For uploaded files
    mime_type: str | None = None  # MIME type for uploaded files


class ActivityPlan(BaseModel):
    """Plan for a single activity within a chapter"""
    name: str
    type: str = "TYPE_DYNAMIC"  # Default activity type
    description: str
    suggested_blocks: list[str] = []  # e.g., ['heading1', 'paragraph', 'quiz']


class ChapterPlan(BaseModel):
    """Plan for a single chapter within a course"""
    name: str
    description: str
    activities: list[ActivityPlan] = []


class CoursePlan(BaseModel):
    """Complete course plan generated by AI"""
    name: str
    description: str
    learnings: str = ""
    tags: str = ""
    chapters: list[ChapterPlan] = []


class CoursePlanningMessage(BaseModel):
    """Single message in the conversation history"""
    role: str  # "user" or "model"
    content: str


class CoursePlanningSessionData(BaseModel):
    """Session data stored in Redis"""
    session_uuid: str
    org_id: int
    language: str = "en"  # Language code for content generation
    planning_iteration_count: int = 0
    max_planning_iterations: int = 10
    activity_iteration_counts: dict[str, int] = {}  # activity_uuid -> iteration count
    max_activity_iterations: int = 6
    message_history: list[CoursePlanningMessage] = []
    current_plan: CoursePlan | None = None
    course_id: int | None = None  # Set after finalization


class StartCoursePlanningSession(BaseModel):
    """Request to start a new course planning session"""
    org_id: int
    prompt: str  # Initial course description from user
    language: str = "en"  # Language code for content generation (e.g., "en", "fr", "de")
    attachments: list[AttachmentData] | None = None  # Context files/links


class SendCoursePlanningMessage(BaseModel):
    """Request to continue planning with a new message"""
    session_uuid: str
    message: str
    current_plan: CoursePlan | None = None  # User-modified plan to iterate on
    attachments: list[AttachmentData] | None = None  # Context files/links


class FinalizeCoursePlanRequest(BaseModel):
    """Request to finalize the plan and create course structure"""
    session_uuid: str
    plan: CoursePlan  # The final plan to create in the database


class GenerateActivityContentRequest(BaseModel):
    """Request to generate content for a specific activity"""
    session_uuid: str
    activity_uuid: str
    activity_name: str
    activity_description: str
    chapter_name: str
    course_name: str
    course_description: str
    prompt: str | None = None  # Additional instructions for content generation


class SaveActivityContentRequest(BaseModel):
    """Request to save AI-generated content to an activity"""
    activity_uuid: str
    content: dict  # ProseMirror JSON content


class CoursePlanningSessionResponse(BaseModel):
    """Response when getting session state"""
    session_uuid: str
    planning_iteration_count: int
    max_planning_iterations: int
    current_plan: CoursePlan | None
    message_history: list[CoursePlanningMessage]
    course_id: int | None = None


class FinalizeCoursePlanResponse(BaseModel):
    """Response after finalizing the course plan"""
    course_uuid: str
    course_id: int
    chapters: list[dict]  # List of created chapters with their activities
